packages:
  - apps/*
  - packages/*

allowBuilds:
  better-sqlite3: true
  esbuild: true
  protobufjs: true

minimumReleaseAgeExclude:
  - "@cline/agents@0.0.65"
  - "@cline/core@0.0.65"
  - "@cline/llms@0.0.65"
  - "@cline/sdk@0.0.65"
  - "@cline/shared@0.0.65"
